site_name: Rmagine Documentation
site_url: https://uos.github.io/rmagine_docs

repo_name: Github
repo_url: https://github.com/uos/rmagine

docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy
  logo: resources/img/rmagine_logo.png
  favicon: resources/img/rmagine_icon.png
  palette:
    primary: blue grey

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - attr_list

validation:
  links:
    absolute_links: relative_to_docs

nav:
  - Home:
    - Overview: index.md
    - Installation: installation.md
    - Integration: integration.md
  - Getting Started:
    - Maps: getting_started/maps.md
    - Sensors: getting_started/sensors.md
    - Simulation: getting_started/simulation.md
    - Problem Modelling: getting_started/problem_modelling.md
    - Noise: getting_started/noise.md
  - Library:
    - Concepts: library/concepts.md
    - Math: library/math.md
    - Memory: library/memory.md
    - Maps: library/maps.md
  - Extra:
    - Tools: extra/tools.md
    - Data: extra/data.md
    - Embree 3: extra/embree3.md
    - CMake - Advanced: extra/cmake_advanced.md
    - Contributions: extra/contributions.md
    - News: extra/news.md